title: demo-learning-lab
description: >-
  A Lab to demo how to create a basic learning lab with Learning Bot auto
  repsonse
template:
  repo: demo-learning-lab-template
  name: demo-learning-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: New step
    actions:
      - type: gate
        left: '"%actions.tree.data.tree%"'
        operator: includes
        right: 'path:new-branch/reademe.md'
    event: push
