title: demo-learning-lab
description: >-
  A Lab to demo how to create a basic learning lab with Learning Bot auto
  repsonse
template:
  repo: demo-learning-lab-template
  name: demo-learning-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
- title: Create a branch
  description: Create a branch for introducing new changes.
  translations:
    es:
      title: Crea una rama
      description: Crea una rama para introducir nuevos cambios. 
  event: create
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: respond
    issue: issue2
    with: branch-create.md
    data:
      thePayload: '%payload%'

# 5
- title: Commit a file
  description: Commit your file to the branch.
  translations:
    es:
      title: Confirma un archivo
      description: Confirma un archivo a tu rama. 
  event: push
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: respond
    issue: issue2
    with: branch-create.md
    data:
      branch: '%payload.ref%'
      url: '%payload.repository.html_url%/compare/%payload.ref%?expand=1'
 
